plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.fireweb.remote'
    compileSdk 35

    signingConfigs {
        stableLocal {
            storeFile file('fireweb-update.jks')
            storePassword 'fireweb-local'
            keyAlias 'fireweb'
            keyPassword 'fireweb-local'
        }
    }

    defaultConfig {
        applicationId "dev.fireweb.remote"
        minSdk 22
        targetSdk 28
        versionCode 3
        versionName "2.1"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableLocal
        }
        release {
            signingConfig signingConfigs.stableLocal
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
