plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.fireweb.remote'
    compileSdk 35

    defaultConfig {
        applicationId "dev.fireweb.remote"
        minSdk 22
        targetSdk 28
        versionCode 7
        versionName "2.5"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
